### ISSUE TITLE
Resize function fails on addition of new content

### ISSUE THREAD

**Issue by ReinderDijkhuis** [AvaLovelace1/mini-hugo-webcomic#1]
Upon adding new Jpeg files to assets/img/comic and creation of the appropriate page, hugo fails to run, throwing the following error message:

> ERROR render of "page" failed: "[path]Sites/mini-hugo-webcomic/layouts/page/archive.html:10:32": execute of template failed: template: page/archive.html:10:32: executing "main" at <$page.comicThumbImgRaw.Resize>: nil pointer evaluating interface {}.Resize
ERROR render of "home" failed: "[path]Sites/mini-hugo-webcomic/layouts/index.html:3:6": execute of template failed: template: index.html:3:6: executing "main" at <partial "comic/comic.html" $comics.lastPage>: error calling partial: "[path]Sites/mini-hugo-webcomic/layouts/partials/comic/comic.html:3:20": execute of template failed: template: partials/comic/comic.html:3:20: executing "partials/comic/comic.html" at <$page.comicImgRaw.Resize>: nil pointer evaluating interface {}.Resize
Built in 40 ms
Error: error building site: render: failed to render pages: render of "page" failed: "[path]/Sites/mini-hugo-webcomic/layouts/comic/single.html:2:6": execute of template failed: template: comic/single.html:2:6: executing "main" at <partial "comic/comic.html" .>: error calling partial: "[path]/Sites/mini-hugo-webcomic/layouts/partials/comic/comic.html:3:20": execute of template failed: template: partials/comic/comic.html:3:20: executing "partials/comic/comic.html" at <$page.comicImgRaw.Resize>: nil pointer evaluating interface {}.Resize

This does not happen if only the default content is present. As far as I can tell, I've followed all instructions correctly and I wonder if there isn't something that works differently between Hugo versions. My version of Hugo is 
>hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended darwin/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=brew

Thanks for sharing this template!

**Comment by AvaLovelace1** [comment]
Hello! It looks like Hugo can't find the new images; perhaps they're named incorrectly? Could you show me your directory structure?

**Comment by ReinderDijkhuis** [comment]
Hi, 

The images are in /Users/[my name]/Dropbox/Sites/mini-hugo-webcomic/assets/img/comic/  and are named green-knights-belt-preamble_001.jpg and green-knights-belt-preamble_thumb.jpg - 

Hugo is being run from within /Users/[my name]/Dropbox/Sites/mini-hugo-webcomic

**Comment by AvaLovelace1** [comment]
What's in the `content/comic` folder?

**Comment by ReinderDijkhuis** [comment]
1.md with the default front matter: 

```
+++
date = 2023-12-30T15:51:48+01:00
hover = 'Add your hover text here.'
+++

Write your comic description or transcript here.
```
Generated using 
`hugo new content --kind comic-page comic/green-knights-belt-preamble/1.md
`

Trying the same but with 001.md and the results are the same

**Comment by AvaLovelace1** [comment]
Could you show me the entire contents of the `comic` folder including all subdirectories and files within them?

**Comment by ReinderDijkhuis** [comment]
Latest version, after generating with 
`hugo new content --kind comic-page comic/green-knights-belt-preamble/001.md `

<img width="612" alt="Schermafbeelding 2023-12-30 om 19 36 43" src="https://github.com/AvaLovelace1/mini-hugo-webcomic/assets/4527163/21cf89a4-ec30-4ea0-ad24-e5646dc810a8">

**Comment by AvaLovelace1** [comment]
Thank you! I see the problem now. You need to place an `_index.md` file in the `green-knights-belt-preamble` folder with the following content:

```
+++
[[cascade]]
title = 'Green Knights Belt Preamble (or whatever you want the title to be)'
chapterID = 'green-knights-belt-preamble'

[_build]
render = 'never'
+++
```

This can be done automatically by running `hugo new content --kind chapter comic/green-knights-belt-preamble/_index.md`, as explained [here](https://github.com/AvaLovelace1/mini-hugo-webcomic/tree/main#adding-a-new-chapter). The important part is the `chapterID` tag, which should be the same string as used in the image filenames. The `chapterID` is what the template uses to find the image files.

I hope this helps! Let me know if you still have issues.

**Comment by ReinderDijkhuis** [comment]
Thank you so much! I can't believe I overlooked that step.

**Comment by AvaLovelace1** [comment]
No problem! Good luck on your comic 😄
